### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../data/NRC-VAD-Lexicon-Aug2018Release/NRC-VAD-Lexicon.txt'

### ISSUE THREAD

**Issue by DanBigioi** [UttaranB127/Text2Gestures#2]
Hey guys, running into the error in the title. I downloaded the dataset from your anonymous link but I think that its missing the NRC-VAD-Lexicon-Aug2018Release/NRC-VAD-Lexicon. If you could edit the read me to tell people to download this too, or update the dataset download link to include it too, it will make it more clear :)

**Comment by UttaranB127** [comment]
Thanks for catching that! It can be downloaded here: https://saifmohammad.com/WebDocs/VAD/NRC-VAD-Lexicon-Aug2018Release.zip, or using the download link in the original webpage: https://saifmohammad.com/WebPages/nrc-vad.html
