### ISSUE TITLE
Pre trained model file is corrupted

### ISSUE THREAD

**Issue by pjyazdian** [UttaranB127/Text2Gestures#3]
HI,

I was trying your repo and the pre-trained model archive file is not working.

**Comment by UttaranB127** [comment]
Hi, could you please elaborate on the error?

**Comment by swastishreya** [comment]
Hi!
When we try to download the pre-trained model, file extraction doesn't work. It says the file cannot be extracted as it is not the correct extension. I think the file naming and compression might be the problem. It would be of great help if you could fix this!
Thank you.

**Comment by UttaranB127** [comment]
The download link is working for me, so I'm unable to find the exact issue. Does this direct download link work for you?
https://drive.google.com/uc?export=download&confirm=S9Dz&id=1-i4dPMxz38bJOU41c8jDmkiiESqZV5-W

**Comment by UttaranB127** [comment]
I've also made it available here: https://obj.umiacs.umd.edu/t2gpretrainedmodel/epoch_2349_loss_0.1874_model.pth.tar

Let me know if this works

**Comment by swastishreya** [comment]
![model_archive](https://user-images.githubusercontent.com/32703974/115027879-e44cca00-9ee1-11eb-9664-0f9839a81a9a.png)

Yes, I tried downloading from both locations. I am facing the above (attached )problem. 
Thank you again.

**Comment by UttaranB127** [comment]
This seems like an error in extraction. Are you able to download the file? The .pth.tar file is not an extractable file, you can directly use it to load the model parameters (the code already does that).

**Comment by swastishreya** [comment]
Oh okay! I assumed we have to extract the file as it had a .tar extension. Thank you very much for letting us know.

**Comment by UttaranB127** [comment]
Are you able to use it?

**Comment by swastishreya** [comment]
Hi! I tried using it, as well as the trained models. But loading the model throws an error. It says that  there are multiple keys missing in the 'state_dict'. So either while loading the model there's a problem or the format in which the model is stored might be a problem. Could you please look into it?

**Comment by swastishreya** [comment]
Hi again,

I think I realised what the error is.. the model expects the state_dict keys as 'module.<some-key>', whereas, the code saves the state_dict keys as '<some-key>'. I am not sure where exactly the change happens. It would be great if you could fix it. Even though just reneaming the keys work as a hack. Thank you.

Please find attached the error here:

<code>
Missing key(s) in state_dict: "module.text_embedding.weight", "module.text_pos_encoder.pe", "module.transformer_encoder.layers.0.self_attn.in_proj_weight", "module.transformer_encoder.layers.0.self_attn.in_proj_bias", "module.transformer_encoder.layers.0.self_attn.out_proj.weight", "module.transformer_encoder.layers.0.self_attn.out_proj.bias", "module.transformer_encoder.layers.0.linear1.weight", "module.transformer_encoder.layers.0.linear1.bias", "module.transformer_encoder.layers.0.linear2.weight", "module.transformer_encoder.layers.0.linear2.bias", "module.transformer_encoder.layers.0.norm1.weight", "module.transformer_encoder.layers.0.norm1.bias", "module.transformer_encoder.layers.0.norm2.weight", "module.transformer_encoder.layers.0.norm2.bias", "module.transformer_encoder.layers.1.self_attn.in_proj_weight", "module.transformer_encoder.layers.1.self_attn.in_proj_bias", "module.transformer_encoder.layers.1.self_attn.out_proj.weight", "module.transformer_encoder.layers.1.self_attn.out_proj.bias", "module.transformer_encoder.layers.1.linear1.weight", "module.transformer_encoder.layers.1.linear1.bias", "module.transformer_encoder.layers.1.linear2.weight", "module.transformer_encoder.layers.1.linear2.bias", "module.transformer_encoder.layers.1.norm1.weight", "module.transformer_encoder.layers.1.norm1.bias", "module.transformer_encoder.layers.1.norm2.weight", "module.transformer_encoder.layers.1.norm2.bias", "module.text_embed.weight", "module.text_embed.bias", "module.text_offsets_to_gestures.weight", "module.text_offsets_to_gestures.bias", "module.quat_pos_encoder.pe", "module.transformer_decoder.layers.0.self_attn.in_proj_weight", "module.transformer_decoder.layers.0.self_attn.in_proj_bias", "module.transformer_decoder.layers.0.self_attn.out_proj.weight", "module.transformer_decoder.layers.0.self_attn.out_proj.bias", "module.transformer_decoder.layers.0.multihead_attn.in_proj_weight", "module.transformer_decoder.layers.0.multihead_attn.in_proj_bias", "module.transformer_decoder.layers.0.multihead_attn.out_proj.weight", "module.transformer_decoder.layers.0.multihead_attn.out_proj.bias", "module.transformer_decoder.layers.0.linear1.weight", "module.transformer_decoder.layers.0.linear1.bias", "module.transformer_decoder.layers.0.linear2.weight", "module.transformer_decoder.layers.0.linear2.bias", "module.transformer_decoder.layers.0.norm1.weight", "module.transformer_decoder.layers.0.norm1.bias", "module.transformer_decoder.layers.0.norm2.weight", "module.transformer_decoder.layers.0.norm2.bias", "module.transformer_decoder.layers.0.norm3.weight", "module.transformer_decoder.layers.0.norm3.bias", "module.transformer_decoder.layers.1.self_attn.in_proj_weight", "module.transformer_decoder.layers.1.self_attn.in_proj_bias", "module.transformer_decoder.layers.1.self_attn.out_proj.weight", "module.transformer_decoder.layers.1.self_attn.out_proj.bias", "module.transformer_decoder.layers.1.multihead_attn.in_proj_weight", "module.transformer_decoder.layers.1.multihead_attn.in_proj_bias", "module.transformer_decoder.layers.1.multihead_attn.out_proj.weight", "module.transformer_decoder.layers.1.multihead_attn.out_proj.bias", "module.transformer_decoder.layers.1.linear1.weight", "module.transformer_decoder.layers.1.linear1.bias", "module.transformer_decoder.layers.1.linear2.weight", "module.transformer_decoder.layers.1.linear2.bias", "module.transformer_decoder.layers.1.norm1.weight", "module.transformer_decoder.layers.1.norm1.bias", "module.transformer_decoder.layers.1.norm2.weight", "module.transformer_decoder.layers.1.norm2.bias", "module.transformer_decoder.layers.1.norm3.weight", "module.transformer_decoder.layers.1.norm3.bias", "module.temporal_smoothing.0.weight", "module.temporal_smoothing.0.bias", "module.temporal_smoothing.1.weight", "module.temporal_smoothing.1.bias", "module.decoder.weight", "module.decoder.bias". 
	Unexpected key(s) in state_dict: "text_embedding.weight", "text_pos_encoder.pe", "transformer_encoder.layers.0.self_attn.in_proj_weight", "transformer_encoder.layers.0.self_attn.in_proj_bias", "transformer_encoder.layers.0.self_attn.out_proj.weight", "transformer_encoder.layers.0.self_attn.out_proj.bias", "transformer_encoder.layers.0.linear1.weight", "transformer_encoder.layers.0.linear1.bias", "transformer_encoder.layers.0.linear2.weight", "transformer_encoder.layers.0.linear2.bias", "transformer_encoder.layers.0.norm1.weight", "transformer_encoder.layers.0.norm1.bias", "transformer_encoder.layers.0.norm2.weight", "transformer_encoder.layers.0.norm2.bias", "transformer_encoder.layers.1.self_attn.in_proj_weight", "transformer_encoder.layers.1.self_attn.in_proj_bias", "transformer_encoder.layers.1.self_attn.out_proj.weight", "transformer_encoder.layers.1.self_attn.out_proj.bias", "transformer_encoder.layers.1.linear1.weight", "transformer_encoder.layers.1.linear1.bias", "transformer_encoder.layers.1.linear2.weight", "transformer_encoder.layers.1.linear2.bias", "transformer_encoder.layers.1.norm1.weight", "transformer_encoder.layers.1.norm1.bias", "transformer_encoder.layers.1.norm2.weight", "transformer_encoder.layers.1.norm2.bias", "text_embed.weight", "text_embed.bias", "text_offsets_to_gestures.weight", "text_offsets_to_gestures.bias", "quat_pos_encoder.pe", "transformer_decoder.layers.0.self_attn.in_proj_weight", "transformer_decoder.layers.0.self_attn.in_proj_bias", "transformer_decoder.layers.0.self_attn.out_proj.weight", "transformer_decoder.layers.0.self_attn.out_proj.bias", "transformer_decoder.layers.0.multihead_attn.in_proj_weight", "transformer_decoder.layers.0.multihead_attn.in_proj_bias", "transformer_decoder.layers.0.multihead_attn.out_proj.weight", "transformer_decoder.layers.0.multihead_attn.out_proj.bias", "transformer_decoder.layers.0.linear1.weight", "transformer_decoder.layers.0.linear1.bias", "transformer_decoder.layers.0.linear2.weight", "transformer_decoder.layers.0.linear2.bias", "transformer_decoder.layers.0.norm1.weight", "transformer_decoder.layers.0.norm1.bias", "transformer_decoder.layers.0.norm2.weight", "transformer_decoder.layers.0.norm2.bias", "transformer_decoder.layers.0.norm3.weight", "transformer_decoder.layers.0.norm3.bias", "transformer_decoder.layers.1.self_attn.in_proj_weight", "transformer_decoder.layers.1.self_attn.in_proj_bias", "transformer_decoder.layers.1.self_attn.out_proj.weight", "transformer_decoder.layers.1.self_attn.out_proj.bias", "transformer_decoder.layers.1.multihead_attn.in_proj_weight", "transformer_decoder.layers.1.multihead_attn.in_proj_bias", "transformer_decoder.layers.1.multihead_attn.out_proj.weight", "transformer_decoder.layers.1.multihead_attn.out_proj.bias", "transformer_decoder.layers.1.linear1.weight", "transformer_decoder.layers.1.linear1.bias", "transformer_decoder.layers.1.linear2.weight", "transformer_decoder.layers.1.linear2.bias", "transformer_decoder.layers.1.norm1.weight", "transformer_decoder.layers.1.norm1.bias", "transformer_decoder.layers.1.norm2.weight", "transformer_decoder.layers.1.norm2.bias", "transformer_decoder.layers.1.norm3.weight", "transformer_decoder.layers.1.norm3.bias", "temporal_smoothing.0.weight", "temporal_smoothing.0.bias", "temporal_smoothing.1.weight", "temporal_smoothing.1.bias", "decoder.weight", "decoder.bias". 
</code>

**Comment by UttaranB127** [comment]
Thanks for pointing this out! I think it has to do with how the project hierarchy is set up, I will look into it. But renaming the keys is actually the best way to fix it for now!
